version: '3.7'
services:
  xnat-web:
    build:
      context: ./xnat
      args:
        XNAT_VER: '1.7.6'
        XNAT_DATASOURCE_DRIVER: 'org.postgresql.Driver'
        XNAT_DATASOURCE_URL: 'jdbc:postgresql://xnat-db/xnat'
        XNAT_DATASOURCE_USERNAME: 'xnat'
        XNAT_DATASOURCE_PASSWORD: 'xnat'
        XNAT_HIBERNATE_DIALECT: 'org.hibernate.dialect.PostgreSQL9Dialect'
        TOMCAT_XNAT_FOLDER: ROOT
        XNAT_ROOT: /data/xnat
        XNAT_HOME: /data/xnat/home
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8000:8000"
      - "8104:8104"
    volumes:
      - ./xnat/plugins:/data/xnat/home/plugins
      - /home/johan/covid19/mnt/xnat/xnat-data/home/logs:/data/xnat/home/logs
      - /home/johan/covid19/mnt/xnat/xnat-data/archive:/data/xnat/archive
      - /home/johan/covid19/mnt/xnat/xnat-data/build:/data/xnat/build
      - /home/johan/covid19/mnt/xnat/xnat-data/cache:/data/xnat/cache
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - xnat-db
    environment:
      - CATALINA_OPTS=-Xms1024m -Xmx4096m -Dxnat.home=/data/xnat/home -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000
      - XNAT_HOME=/data/xnat/home
  xnat-db:
    build: ./postgres
    restart: unless-stopped
    expose:
      - "5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  xnat-deidentify:
    image: registry.gitlab.com/um-cds/projects/covid-19/xnatdownloadservice:latest
    ports:
      - "8081:80"
    volumes:
      - ./xnat-download-service/config.json:/app/config.json
      - ./lookup/patientLookup.json:/app/patientLookup.json
      - ./lookup/lookup.properties:/app/lookup.properties
      - /home/johan/covid19/mnt/xnat/ctp_import:/app/DOWNLOADS
    depends_on:
      - xnat-web
  ctp:
    image: jvsoest/ctp
    ports:
      - "8082:80"
    volumes:
      - ./ctp/config.xml:/CTP/config.xml
      - ./lookup:/lookup
      - ./ctp/anonymizer.properties:/anonymizer.properties
      - ./ctp/xnat.script:/xnat.script
      - /home/johan/covid19/mnt/xnat/ctp_import:/_IMPORT
    depends_on:
      - xnat-web
  

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  192.169.230.1/24
