<script>
 <p t="SHORTNAME">covid19mumcres</p>
 <e en="T" t="00100020" n="PatientID">@keep()</e>
 <e en="T" t="00104000" n="PatientComments">@always()Project: @param(@SHORTNAME); Subject: @contents(PatientID); Session: @contents(AccessionNumber)_@contents(StudyDescription, "[^0-9a-zA-Z]+", "_")</e>
 <e en="T" t="00081030" n="StudyDescription">@keep()</e>
 <e en="T" t="00080050" n="AccessionNumber">@keep()</e>
</script>
